config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords',registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    root to: "users/sessions#new"
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
  end
  
  
  

  resources :users,only: [:index, :show, :new] do 
    resources :posts, only: [:index, :show,:new, :create, :destroy] do    
      post :like, on: :member
      resources :comments, only: [:new, :create, :destroy] 
      
  
    end
end
namespace :api do
  resources :user, only: [:show, :index] do
    resources :post, only: [:show] do
      resources :comment, only: [:index , :create] do
    end
  end
end
end





  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'posts_id'

  def self.update_comments_counter(ide, cuantity)
    Post.where(id: ide).update(CommentsCounter: cuantity)
  end
end

app/controllers/api/comment_controller.rb
class Api::CommentController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  include Devise::Controllers::Helpers

  def index
    @comments = Comment.where(author_id: params[:user_id])
    render json: @comments
  end

  def create
    current_user = warden.authenticate!(scope: :user)

    comment = Comment.new(author_id: current_user.id, posts_id: params[:post_id], Text: params[:text])

    if comment.save
      render json: comment, status: :created
    else
      render json: { errors: comment.errors }, status: :unprocessable_entity
    end
  end

  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @stylesheet = 'post/show'
    @comment = Comment.new
  end

  def destroy
    return unless user_signed_in?

    @current_user = current_user
    comment = Comment.find(params[:id])

    comment.destroy

    redirect_to user_path(params[:id])
  end

  def create
    return unless user_signed_in?

    @current_user = current_user

    @comment = Comment.new(comment_params.merge({ Text: params[:comment][:text], posts_id: params[:post_id],
                                                  author_id: @current_user.id }))

    if @comment.save
      flash[:notice] = 'post created successfully'
      redirect_to user_post_path(user_id: @current_user.id, id: params[:post_id])

    else
      flash[:alert] = 'Error whe the post was created'
      render 'new'

    end
  end

  private

  def comment_params
    params.require(:comment).permit(:Text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Authorid:</strong>
    <%= comment.AuthorId %>
  </p>

  <p>
    <strong>Postid:</strong>
    <%= comment.PostId %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= comment.Text %>
  </p>

</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= form_with(model: @comment, local: true, url: user_post_comments_path )  do |form| %>
  
  <%= form.label :text %>
  <%= form.text_area :text %>
  
  <%= form.submit %>

<% end %>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>
  
  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>