config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords',registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    root to: "users/sessions#new"
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
  end
  
  
  

  resources :users,only: [:index, :show, :new] do 
    resources :posts, only: [:index, :show,:new, :create, :destroy] do    
      post :like, on: :member
      resources :comments, only: [:new, :create, :destroy] 
      
  
    end
end
namespace :api do
  resources :user, only: [:show, :index] do
    resources :post, only: [:show] do
      resources :comment, only: [:index , :create] do
    end
  end
end
end





  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :email, presence: true, uniqueness: true
  validates :Name, presence: true
  validates :PostsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.see_3recent_posts(id)
    Post.includes(:user).where(author_id: id).last(3)
  end
end

app/controllers/api/user_controller.rb
class Api::UserController < ApplicationController
  def index
    @all = User.all

    render json: @all
  end

  def show
    @posts = Post.where(author_id: params[:id])

    render json: @posts
  end

  def comments
    post = Post.find(params[:post_id])
    @comments = post.comments
    render json: @comments
  end

  def add_comment
    post = Post.find(params[:post_id])
    comment = post.comments.build(content: params[:content], user_id: current_user.id)
    if comment.save
      render json: { success: true, message: 'Comment created successfully' }
    else
      render json: { success: false, message: 'Comment could not be created' }
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  layout 'application'
  def index
    @stylesheet = 'user/user'
    @users = User.all
    @posts_count_by_user = {}
    @users.each do |user|
      @posts_count_by_user[user.id] = Post.where(author_id: user.id).count
    end
  end

  def show
    @stylesheet = 'user/show'
    @users = User.find_by(id: params[:id]) # object no proper of the database we use new instead of find
    @posts = User.see_3recent_posts(params[:id])
    @posts_counter = Post.where(author_id: params[:id]).count
    @comments_count_by_post = {}
    @likes_count_by_post = {}
    @posts.each do |post|
      @comments_count_by_post[post.id] = Comment.where(posts_id: post.id, author_id: params[:id]).count
      @likes_count_by_post[post.id] = Post.group(:id).find_by(id: post.id, author_id: params[:id]).LikesCounter
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    @stylesheet = 'post/post'
    super
  end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    @stylesheet = 'post/post'
    super
  end

  # POST /resource/password
  #
  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    @stylesheet = 'post/post'
    super
  end

  def create
    @stylesheet = 'post/post'
    super
  end

  # PUT /resource/password

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    @stylesheet = 'post/post'
    super
  end

  # POST /resource
  def create
    @user = User.new(user_params)
    @user.PostsCounter ||= 0
    if @user.save
      redirect_to user_session_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
    end
  end

  private

  def user_params
    params.require(:user).permit(:Name, :Photo, :Bio, :email, :password)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(_resource)
    # Use the path of your desired view here
    users_path
    # root_path
  end

  # GET /resource/sign_in
  def new
    @stylesheet = 'user/login'
    @user = User.new
  end

  # POST /resource/sign_in
  # def create
  #   @stylesheet = 'post/post'
  #   super
  # end

  # DELETE /resource/sign_out

  # def after_sign_out_path_for(resource_or_scope)
  #   root_path
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  layout 'application'

  def index
    @stylesheet = 'user/user'
    @users = User.all
    @posts_count_by_user = {}

    @users.each do |user|
      @posts_count_by_user[user.id] = Post.where(author_id: user.id).count
    end
    return unless user_signed_in?

    @current_user = current_user
  end

  def show
    @stylesheet = 'user/show'
    @users = User.find_by(id: params[:id]) # object no proper of the database we use new instead of find
    @posts = User.see_3recent_posts(params[:id])
    @posts_counter = Post.where(author_id: params[:id]).count
    @comments_count_by_post = {}
    @likes_count_by_post = {}
    @total_posts = {}
    @t = Post.find_by(author_id: 3)
    return unless user_signed_in?

    @current_user = current_user

    @posts.each do |post|
      @comments_count_by_post[post.id] = Comment.where(posts_id: post.id).count
      @likes_count_by_post[post.id] = Post.group(:id).find_by(id: post.id, author_id: params[:id]).LikesCounter
      @total_posts[post.id] = Post.find_by(id: post.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bio.html.erb
  <li id="p_item_user_show"> 
  <h2 class="numPost_user_show">Post <%= post.id %></h2>
  <h3 class="textPost_user_show"><%= post.Title %> </h3>
   <p class="textPost_user_show"><%= post.Text %> </p>
<h3 class="comLikesPost_user_show">
Comments: <%= @comments_count_by_post[post.id] || 0 %>, 
Likes: <%= @likes_count_by_post[post.id] || 0 %>,
  </h3>
  <% if can? :destroy, @total_posts[post.id] %>
      <%= button_to "Delete", user_post_path(@current_user,post) , method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
  </li>

app/views/users/_user.html.erb
<li class="contentIconName_user_index"> 
  
  <div class="contentIcon_user_index">  
      <%= image_tag(user.Photo, alt: "No available", class: "contentIcon_user_index", width: "100px", height: "100px" ) %> 
      
  </div> 
  
  <div class="contentNamePost_user_index">
      <h2 class="name_user_index"><%=user.Name%></h2>
       <h3 class="numberPosts_user_index">Number of posts:  <%= @posts_count_by_user[user.id] %></h3> 
      </div> 
      
</li>

app/views/users/index.html.erb
  <ul class="subParentContent_user_index">

  <% @users.each do |user| %>
    
    <%= render "users/user", user: user %>
    
    <% end %>
    
    <h1 class="sign_out">  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </h1>
  </ul>

  

app/views/users/new.html.erb
<h1>New post</h1>

<%= form_with(model: @post, local: true, url: new_user_post_path(:user_id => @current_user )) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text %>
  <%= form.text_area :text %>
  
  <%= form.submit %>

<% end %>

app/views/users/show.html.erb
  <div class="subParentContent_user_show">
  <div class="contentIconName_user_show"> 
  <div class="contentIcon_user_show">  <%= image_tag(@users.Photo, alt: "No available", class: "contentIcon_user_show", width: "100px", height: "100px")  %>  
  </div>
  <div class="contentNamePost_user_show">
      <h2 class="name_user_show"><%=  @users.Name%></h2>
       <h3 class="numberPosts_user_show">Number of posts: <%= @posts_counter %></h3> 
      </div> 
  </div>
  <div class="bio_user_show"> <p class="InBio_user_show"> Bio  <br><br> 
  <%= @users.Bio %>
  </p>

  </div>
  
  <ul id="posts_li_user_show">

   
    <% @posts.each do |post|%>
    <%= render "users/bio", post: post %>
   
<% end %>

  </ul>
  <%= link_to "Create new post", new_user_post_path(:user_id => params[:id]) , class: "btn btn-primary" %>
  <button type="button" class="seeAllpostsButton_user_show">See all posts</button>
  </div>
  
  
  </div>