config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords',registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    root to: "users/sessions#new"
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
  end
  
  
  

  resources :users,only: [:index, :show, :new] do 
    resources :posts, only: [:index, :show,:new, :create, :destroy] do    
      post :like, on: :member
      resources :comments, only: [:new, :create, :destroy] 
      
  
    end
end
namespace :api do
  resources :user, only: [:show, :index] do
    resources :post, only: [:show] do
      resources :comment, only: [:index , :create] do
    end
  end
end
end





  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :comments, foreign_key: :posts_id, dependent: :destroy
  has_many :likes, foreign_key: :posts_id, dependent: :destroy

  validates :Title, length: { maximum: 250 }, presence: true
  validates :CommentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :LikesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.update_post_counter(ide, newcounter)
    User.find_by(id: ide).update(PostsCounter: newcounter)
  end

  def self.return5_recent_post(id)
    Comment.where(author_id: id).last(5)
  end
end

app/controllers/api/post_controller.rb
class Api::PostController < ApplicationController
  def show
    @posts = Post.find_by(id: params[:id])

    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'application'
  load_and_authorize_resource
  def index
    @stylesheet = 'post/post'
    @users = User.find_by(id: params[:user_id]) # object no proper of the database we use new instead of find
    @posts_counter = Post.where(author_id: params[:user_id]).count
    @comments_count_by_post = {}
    @likes_count_by_post = {}
    @comments_by_post = {}
    @users_by_post = {}
    @posts = User.see_3recent_posts(params[:user_id])
    @posts.each do |post|
      @comments_count_by_post[post.id] = Comment.where(posts_id: post.id, author_id: params[:user_id]).count
      @likes_count_by_post[post.id] = Post.group(:id).find_by(id: post.id, author_id: params[:user_id]).LikesCounter
      @comments_by_post[post.id] = Comment.includes(:user).where(author_id: params[:user_id], posts_id: post.id)
    end
  end

  def destroy
    return unless user_signed_in?

    @current_user = current_user
    post = Post.find(params[:id])
    user = User.find(params[:user_id])
    post.comments.destroy_all
    post.destroy
    user.update(PostsCounter: user.posts.count)
    redirect_to user_path(params[:id])
  end

  def show
    @stylesheet = 'post/show'
    @post_id = Post.find(params[:id])
    @post = Post.find_by(id: params[:id])
    @comments_count_by_post = Comment.where(posts_id: params[:id]).count
    @likes_count_by_post = Like.includes(:post).find_by(posts_id: params[:id])

    if @likes_count_by_post.nil?

      @likes_count_by_post = Like.create(author_id: @current_user.id, posts_id: params[:id])
    else
      @likes_count_by_post.post.LikesCounter

    end

    @comments_by_post = Comment.includes(:post).where(posts_id: params[:id])
  end

  def like
    return unless user_signed_in?

    @current_user = current_user

    @like = Like.find_by(author_id: @current_user.id, posts_id: params[:id])
    if @like
      @likes_counter = @like.post.LikesCounter
      if @like.post.update(LikesCounter: @likes_counter + 1)

        flash[:notice] = 'Like created successfully'
        redirect_to user_post_path
      else
        flash[:alert] = 'Error whe the like was created'
        render 'new'
      end
    else
      flash[:alert] = 'Post not found'
      Like.create(author_id: @current_user.id, posts_id: 33)

      Like.find_by(author_id: @current_user.id, posts_id: 33).post.LikesCounter = 1
    end
  end

  def new
    @stylesheet = 'post/show'
    @post = Post.new
    return unless user_signed_in?

    @current_user = current_user
  end

  def create
    @stylesheet = 'post/show'
    return unless user_signed_in?

    @current_user = current_user

    @post = Post.new(author_id: @current_user.id, Title: params[:post][:Title], Text: params[:post][:Text],
                     CommentsCounter: 0, LikesCounter: 0)
    if @post.save
      flash[:notice] = 'post created successfully'
      ide = params[:id].to_i
      puts ide
      redirect_to user_path(id: @current_user.id)

    else
      flash[:alert] = 'Error whe the post was created'
      render 'new'

    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_user_post.html.erb
<li id="p_item_post_index"> 
    
<div class="postSection_post_index">  <h2 class="numPost_post_index">Post <%= post.id %> </h2>
<h2><%= post.Title %></h2>
<p class="textPost_post_index_<%= post.id %>"> <%= post.Text%> </p>
<h3 class="comLikesPost_post_index">
Comments: <%= @comments_count_by_post[post.id] || 0 %>, 
Likes: <%= @likes_count_by_post[post.id] || 0 %>,
</h3>
</div>
<ul class="commentSection_post_index"> 


<% @comments_by_post[post.id].each do |comment|%>
   
    <div class="commentByUser_post_index_<%= comment.id %>">
<h2 class="userComment_post_index"><%= comment.user.Name %> : <h3 
class="commentMessage_post_index"> <%= comment.Text %> </h3> 
</h2>
 </div> 

<% end %>

</ul>



</li>

app/views/posts/index.html.erb
  
  <div class="subParentContent_post_index">
  <div class="contentIconName_post_index"> 
  <div class="contentIcon_post_index">  <%= image_tag(@users.Photo, alt: "No available", class: "contentIcon", width: "100px", height: "100px" ) %>  
  </div> 
  <div class="contentNamePost_post_index">
      <h2 class="name_post_index"><%= @users.Name %></h2>
       <h3 class="numberPosts_post_index">Number of posts: <%= @posts_counter%></h3> 
      </div> 
  </div>

  <ul id="posts_li_post_index">
  <% @posts.each  do |post|  %>
    
    <%= render "posts/user_post", post: post %>


   
    <%end%>

  </ul>
  
  <button type="button" class="seeAllpostsButton_post_index">Pagination</button>
  </div>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post,url: user_posts_path(:user_id => 1), method: :post, local: true)  do |form| %>
  <%= form.label :title %>
  <%= form.text_field :Title %>

  <%= form.label :text %>
  <%= form.text_area :Text %>
  
  <%= form.submit %>

<% end %>

app/views/posts/show.html.erb
<div class="postComment_post_show">

    
        <div class="postSection_post_show"> 
         <h2 class="numPost_post_show">Post <%= @likes_count_by_post.post.id %> By  <%= @post.user.Name %></h2>
        <h3 class="comLikesPost_post_show">
        Comments: <%= @comments_count_by_post %>, 
        Likes: <%= @likes_count_by_post.post.LikesCounter %> </h3>
        <h2 class="title_post_show"><%= @post.Title %>  </h2>
        <p class="textPost_post_show_<%= @post.id %>">
        <%= @post.Text %> 
        </p>

        <%= button_to 'Like', like_user_post_path(:user_id => 1), method: :post %>

        <%= @like %>

        </div>
        
        <ul class="commentSection_post_show"> 

        <% @comments_by_post.each do |comment| %>
        <li class="commentByUser_post_show_<%= comment.id %>">
        <h2 class="userComment_post_show"> <%= comment.user.Name %> :  
         <h3 class="commentMessage_post_show_<%= comment.id %>"> <%= comment.Text %></h3> 
        </h2>
        <% if can? :destroy, comment %>
        <%= button_to "Delete", user_post_comment_path(@current_user,comment, id: comment.id) , method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
        
         </li> 
         <% end %>

        </ul>
        <%= link_to "Create new comment", new_user_post_comment_path(:user_id => @current_user,:post_id => @post_id.id) , class: "btn btn-primary" %>        
        
        
  </div>