config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', passwords: 'users/passwords',registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    root to: "users/sessions#new"
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
  end
  
  
  

  resources :users,only: [:index, :show, :new] do 
    resources :posts, only: [:index, :show,:new, :create, :destroy] do    
      post :like, on: :member
      resources :comments, only: [:new, :create, :destroy] 
      
  
    end
end
namespace :api do
  resources :user, only: [:show, :index] do
    resources :post, only: [:show] do
      resources :comment, only: [:index , :create] do
    end
  end
end
end





  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # root "articles#index"
end

app/helpers/create_users_helper.rb
module CreateUsersHelper
end

app/views/create_users/_create_user.html.erb
<div id="<%= dom_id create_user %>">
  <p>
    <strong>Name:</strong>
    <%= create_user.Name %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= create_user.Photo %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= create_user.Bio %>
  </p>

  <p>
    <strong>Postscounter:</strong>
    <%= create_user.PostsCounter %>
  </p>

  <p>
    <strong>Git:</strong>
    <%= create_user.git %>
  </p>

  <p>
    <strong>Add:</strong>
    <%= create_user.add %>
  </p>

  <p>
    <strong>.:</strong>
    <%= create_user.. %>
  </p>

</div>

app/views/create_users/_form.html.erb
<%= form_with(model: create_user) do |form| %>
  <% if create_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(create_user.errors.count, "error") %> prohibited this create_user from being saved:</h2>

      <ul>
        <% create_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :Photo, style: "display: block" %>
    <%= form.text_field :Photo %>
  </div>

  <div>
    <%= form.label :Bio, style: "display: block" %>
    <%= form.text_field :Bio %>
  </div>

  <div>
    <%= form.label :PostsCounter, style: "display: block" %>
    <%= form.text_field :PostsCounter %>
  </div>

  <div>
    <%= form.label :git, style: "display: block" %>
    <%= form.text_field :git %>
  </div>

  <div>
    <%= form.label :add, style: "display: block" %>
    <%= form.text_field :add %>
  </div>

  <div>
    <%= form.label :., style: "display: block" %>
    <%= form.text_field :. %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/create_users/edit.html.erb
<h1>Editing create user</h1>

<%= render "form", create_user: @create_user %>

<br>

<div>
  <%= link_to "Show this create user", @create_user %> |
  <%= link_to "Back to create users", create_users_path %>
</div>

app/views/create_users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Create users</h1>

<div id="create_users">
  <% @create_users.each do |create_user| %>
    <%= render create_user %>
    <p>
      <%= link_to "Show this create user", create_user %>
    </p>
  <% end %>
</div>

<%= link_to "New create user", new_create_user_path %>

app/views/create_users/new.html.erb
<h1>New create user</h1>

<%= render "form", create_user: @create_user %>

<br>

<div>
  <%= link_to "Back to create users", create_users_path %>
</div>

app/views/create_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @create_user %>

<div>
  <%= link_to "Edit this create user", edit_create_user_path(@create_user) %> |
  <%= link_to "Back to create users", create_users_path %>

  <%= button_to "Destroy this create user", @create_user, method: :delete %>
</div>